# Dockerfile.database

FROM alpine:latest

# Install SQLite
RUN apk --update add sqlite

# Create a directory for the SQLite database file
RUN mkdir /data

# Set the working directory
WORKDIR /data

# Copy a script that will keep the container running
COPY run.sh /data/run.sh

# Grant execute permissions to the script
RUN chmod +x /data/run.sh

# Expose a volume for persistence
VOLUME /data

# Command to run when the container starts
CMD ["/data/run.sh"]
