version: "3"
services:
    db:
        image: nouchka/sqlite3:latest
        volumes:
            - ./data/db:/root/db
        environment:
            - SQLITE3_DB=db.sqlite3
        restart: on-failure

    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        ports:
            - "5001:5000"
        volumes:
            - ./data/db:/root/db
        restart: always
        depends_on:
            - db
