version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: crondatabase
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mseweb
      MYSQL_DATABASE: cron_db
      MYSQL_USER: mseweb
      MYSQL_PASSWORD: mseweb
    ports:
      - "3306:3306"
    restart: always