version: '3'

services:
  database:
    image: sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/db/
    restart: always
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    restart: always
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    restart: always

  
