# Dockerfile.database

FROM alpine:latest

# Install SQLite
RUN apk --update add sqlite

# Create a directory for the SQLite database file
RUN mkdir /data

# Set the working directory
WORKDIR /data

# Expose a volume for persistence
VOLUME /data

