version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    restart: always

  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    container_name: crondatabase
    volumes:
      - ./data:/data
    restart: always
